SELECT TOP (1000) [Country]
      ,[Region]
      ,[Happiness Rank]
      ,[Happiness Score]
      ,[Standard Error]
      ,[Economy (GDP per Capita)]
      ,[Family]
      ,[Health (Life Expectancy)]
      ,[Freedom]
      ,[Trust (Government Corruption)]
      ,[Generosity]
      ,[Dystopia Residual]
  FROM [Portfolio Project World Happiness].[dbo].[Switzerland]
